import "dotenv/config";
import { DateTime } from "luxon";
import { EquGpsError, FetchHttpTransport, SessionTokenProvider, createOfficialEquGpsClient, createWebRouteClient, createWebRunsClient, createWebSpeedEventsClient, createWebVehicleDetailsClient, executeReadOnlyWithSessionToken, parseEquGpsConfig, type HttpRequest, type HttpResponse, type HttpTransport } from "@taxi-gps/equgps";

class TimedTransport implements HttpTransport { public readonly timings: string[] = []; private readonly inner = new FetchHttpTransport(); public async execute(request: HttpRequest): Promise<HttpResponse> { const started = performance.now(); try { return await this.inner.execute(request); } finally { this.timings.push(`${request.operation}=${Math.round(performance.now() - started)}ms`); } } }
async function run(): Promise<void> {
  const config = parseEquGpsConfig({ officialBaseUrl: process.env.EQUGPS_BASE_URL ?? "", webBaseUrl: process.env.EQUGPS_WEB_BASE_URL ?? "", email: process.env.EQUGPS_EMAIL ?? "", password: process.env.EQUGPS_PASSWORD ?? "", requestTimeoutMs: Number(process.env.EQUGPS_REQUEST_TIMEOUT_MS) });
  const transport = new TimedTransport(); const official = createOfficialEquGpsClient(config, transport); const runs = createWebRunsClient(config, transport); const mode1 = createWebVehicleDetailsClient(config, transport); const mode2 = createWebSpeedEventsClient(config, transport); const route = createWebRouteClient(config, transport); const provider = new SessionTokenProvider(() => official.createSession());
  let session = false, runsCount: number | undefined, mode1Trips: number | undefined, movement = false, mode2Events: number | undefined, routeTrips: number | undefined, routePoints: number | undefined, distanceMatches: boolean | undefined; let failure: EquGpsError | undefined; let unknownFailure = false;
  try { await provider.getToken(); session = true; const allRuns = await executeReadOnlyWithSessionToken(provider, (token) => runs.getRuns(token)); runsCount = allRuns.length; const selected = allRuns.find((item) => item.distanceMeters > 0); if (selected === undefined) throw new Error(); const params = { deviceId: selected.deviceId, date: DateTime.now().setZone("Europe/Kyiv").toFormat("yyyy-LL-dd") }; const details = await executeReadOnlyWithSessionToken(provider, (token) => mode1.getVehicleDayDetails(token, params)); mode1Trips = details.trips.length; movement = details.movementDurationSeconds !== null; const speed = await executeReadOnlyWithSessionToken(provider, (token) => mode2.getExternalSpeedReport(token, params)); mode2Events = speed.events.length; const vehicleRoute = await executeReadOnlyWithSessionToken(provider, (token) => route.getVehicleRoute(token, params)); routeTrips = vehicleRoute.trips.length; routePoints = vehicleRoute.points.length; distanceMatches = details.distanceMeters !== null && vehicleRoute.distanceMeters !== null && Math.abs(details.distanceMeters - vehicleRoute.distanceMeters) <= 0.01; } catch (error) { if (error instanceof EquGpsError) failure = error; else { unknownFailure = true; process.exitCode = 1; } } finally { console.log(`session success: ${session}`); if (runsCount !== undefined) console.log(`runs count: ${runsCount}`); if (mode1Trips !== undefined) { console.log("mode1 success: true"); console.log(`mode1 trip count: ${mode1Trips}`); console.log(`mode1 movement duration available: ${movement}`); } if (mode2Events !== undefined) { console.log("mode2 success: true"); console.log(`mode2 event count: ${mode2Events}`); } if (routeTrips !== undefined && routePoints !== undefined) { console.log("route success: true"); console.log(`route trip count: ${routeTrips}`); console.log(`route point count: ${routePoints}`); console.log(`route distance matches mode1: ${distanceMatches}`); } console.log(`durations: ${transport.timings.join(", ")}`); console.log(`http requests: ${transport.timings.length}`); if (failure !== undefined) { console.log(`errorType: ${failure.name}`); if (failure.operation !== undefined) console.log(`operation: ${failure.operation}`); if (failure.status !== undefined) console.log(`status: ${failure.status}`); process.exitCode = 1; } else if (unknownFailure) console.log("errorType: unknown"); }
}
void run();
