import { Injectable } from "@nestjs/common";
import { Prisma } from "../../generated/prisma/client";
import { buildSettingsUpdatedAuditEvent, type AuditUserActor, AuditEventRepository } from "../audit";
import { validateGeoJsonPolygon, validateInactivitySettings, validateMinimumDailyDistanceMeters, validatePositionFreshnessSeconds, validateRevision, validateRuleEnabled, validateSpeedSettings, validateTimezone, validateUpdatedAt } from "../alert-settings/alert-settings.validation";
import { SettingsChangeNotifier, type SettingsChangeKind } from "../alert-settings";
import { DatabaseService } from "../database/database.service";
import { validateTripStopAnalyticsPolicy } from "../trip-stop-analytics";
import { ADMIN_SETTINGS_FIELDS, type AdminSettingsPatch, type AdminSettingsResponse, AdminSettingsError, type StoredSettings } from "./admin-settings.types";

const SELECT = { timezone: true, minimumDailyDistanceMeters: true, positionFreshnessSeconds: true, speedRuleEnabled: true, citySpeedLimitKph: true, outsideCitySpeedLimitKph: true, speedToleranceKph: true, speedingConfirmationUpdates: true, inactivityRuleEnabled: true, inactivityDistanceMeters: true, inactivityDurationMinutes: true, tripMovementSpeedKph: true, tripMovementConfirmationSeconds: true, tripStopConfirmationSeconds: true, tripDataGapSeconds: true, cityGeofenceGeoJson: true, updatedAt: true, revision: true } as const;
function record(value: unknown): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new AdminSettingsError("INVALID_INPUT"); return value as Record<string, unknown>; }
function geofence(value: unknown): string { const polygon = validateGeoJsonPolygon(value); return polygon === null ? "not configured" : `${polygon.coordinates.length} rings, ${polygon.coordinates.reduce((sum, ring) => sum + ring.length, 0)} points`; }
function present(row: StoredSettings): AdminSettingsResponse { const speed = validateSpeedSettings(row); const inactivity = validateInactivitySettings(row); const tripStop = validateTripStopAnalyticsPolicy(row); const polygon = validateGeoJsonPolygon(row.cityGeofenceGeoJson); return Object.freeze({ timezone: validateTimezone(row.timezone), minimumDailyDistanceMeters: validateMinimumDailyDistanceMeters(row.minimumDailyDistanceMeters), positionFreshnessSeconds: validatePositionFreshnessSeconds(row.positionFreshnessSeconds), speedRuleEnabled: validateRuleEnabled(row.speedRuleEnabled), citySpeedLimitKph: speed.citySpeedLimitKph, outsideCitySpeedLimitKph: speed.outsideCitySpeedLimitKph, speedToleranceKph: speed.speedToleranceKph, speedingConfirmationUpdates: speed.speedingConfirmationUpdates, inactivityRuleEnabled: validateRuleEnabled(row.inactivityRuleEnabled), inactivityDistanceMeters: inactivity.inactivityDistanceMeters, inactivityDurationMinutes: inactivity.inactivityDurationMinutes, ...tripStop, cityGeofence: Object.freeze({ configured: polygon !== null, ringCount: polygon?.coordinates.length ?? 0, pointCount: polygon?.coordinates.reduce((n, ring) => n + ring.length, 0) ?? 0 }), updatedAt: validateUpdatedAt(row.updatedAt), revision: validateRevision(row.revision) }); }
function patch(value: unknown): AdminSettingsPatch { const input = record(value); const allowed = new Set(["revision", ...ADMIN_SETTINGS_FIELDS]); if (Object.keys(input).some((key) => !allowed.has(key)) || !("revision" in input)) throw new AdminSettingsError("INVALID_INPUT"); const result: Record<string, unknown> = { revision: validateRevision(input.revision) }; for (const field of ADMIN_SETTINGS_FIELDS) if (field in input) result[field] = input[field]; if (Object.keys(result).length === 1) throw new AdminSettingsError("INVALID_INPUT"); return result as AdminSettingsPatch; }
function validateMerged(current: StoredSettings, update: AdminSettingsPatch): StoredSettings { const next = { ...current, ...update } as StoredSettings; try { validateTimezone(next.timezone); validateMinimumDailyDistanceMeters(next.minimumDailyDistanceMeters); validatePositionFreshnessSeconds(next.positionFreshnessSeconds); validateRuleEnabled(next.speedRuleEnabled); validateRuleEnabled(next.inactivityRuleEnabled); validateSpeedSettings(next); validateInactivitySettings(next); validateTripStopAnalyticsPolicy(next); validateGeoJsonPolygon(next.cityGeofenceGeoJson); return next; } catch { throw new AdminSettingsError("INVALID_INPUT"); } }
function changes(current: StoredSettings, next: StoredSettings) { return ADMIN_SETTINGS_FIELDS.flatMap((field) => { const previous = field === "cityGeofenceGeoJson" ? geofence(current[field]) : current[field] as string | number | boolean | null; const after = field === "cityGeofenceGeoJson" ? geofence(next[field]) : next[field] as string | number | boolean | null; return JSON.stringify(previous) === JSON.stringify(after) ? [] : [Object.freeze({ field, previous, next: after })]; }); }
function resetKinds(changed: ReturnType<typeof changes>): ReadonlySet<SettingsChangeKind> { const reset = new Set<SettingsChangeKind>(); if (changed.some((item) => ["speedRuleEnabled", "citySpeedLimitKph", "outsideCitySpeedLimitKph", "speedToleranceKph", "speedingConfirmationUpdates", "cityGeofenceGeoJson"].includes(item.field))) reset.add("speeding"); if (changed.some((item) => ["inactivityRuleEnabled", "inactivityDistanceMeters", "inactivityDurationMinutes"].includes(item.field))) reset.add("inactivity"); return reset; }

@Injectable()
export class AdminSettingsService {
  public constructor(private readonly database: DatabaseService, private readonly audit: AuditEventRepository, private readonly notifier: SettingsChangeNotifier) {}
  public async get(): Promise<AdminSettingsResponse> { try { const row = await this.database.getClient().applicationSettings.findUnique({ where: { id: 1 }, select: SELECT }); if (!row) throw new AdminSettingsError("UNAVAILABLE"); return present(row); } catch (error) { if (error instanceof AdminSettingsError) throw error; throw new AdminSettingsError("UNAVAILABLE"); } }
  public async update(actor: AuditUserActor, input: unknown): Promise<AdminSettingsResponse> {
    const update = patch(input); let result: { row: StoredSettings; changes: ReturnType<typeof changes> };
    try { result = await this.database.getClient().$transaction(async (tx) => {
      const current = await tx.applicationSettings.findUnique({ where: { id: 1 }, select: SELECT }); if (!current) throw new AdminSettingsError("UNAVAILABLE");
      const next = validateMerged(current, update); const auditChanges = changes(current, next); if (!auditChanges.length) return { row: current, changes: auditChanges };
      const written = await tx.applicationSettings.updateMany({ where: { id: 1, revision: update.revision }, data: { timezone: next.timezone, minimumDailyDistanceMeters: next.minimumDailyDistanceMeters, positionFreshnessSeconds: next.positionFreshnessSeconds, speedRuleEnabled: next.speedRuleEnabled, citySpeedLimitKph: next.citySpeedLimitKph, outsideCitySpeedLimitKph: next.outsideCitySpeedLimitKph, speedToleranceKph: next.speedToleranceKph, speedingConfirmationUpdates: next.speedingConfirmationUpdates, inactivityRuleEnabled: next.inactivityRuleEnabled, inactivityDistanceMeters: next.inactivityDistanceMeters, inactivityDurationMinutes: next.inactivityDurationMinutes, tripMovementSpeedKph: next.tripMovementSpeedKph, tripMovementConfirmationSeconds: next.tripMovementConfirmationSeconds, tripStopConfirmationSeconds: next.tripStopConfirmationSeconds, tripDataGapSeconds: next.tripDataGapSeconds, cityGeofenceGeoJson: next.cityGeofenceGeoJson === null ? Prisma.DbNull : next.cityGeofenceGeoJson as Prisma.InputJsonValue, revision: { increment: 1 } } });
      if (written.count !== 1) throw new AdminSettingsError("CONFLICT"); const row = await tx.applicationSettings.findUniqueOrThrow({ where: { id: 1 }, select: SELECT }); await this.audit.append(tx, buildSettingsUpdatedAuditEvent(actor, { changes: auditChanges })); return { row, changes: auditChanges };
    }); } catch (error) { if (error instanceof AdminSettingsError) throw error; throw new AdminSettingsError("UNAVAILABLE"); }
    const reset = resetKinds(result.changes); if (reset.size) this.notifier.notify(reset); return present(result.row);
  }
}
