"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { AuthPermission } from "@/lib/auth/auth-contract";
import { parseOneTimePasswordResult } from "@/lib/admin-users/admin-users-contract";
import { OneTimePassword } from "./one-time-password";
import { PermissionSelector } from "./permission-selector";
function errorMessage(value: unknown): string { return typeof value === "object" && value !== null && "message" in value && typeof value.message === "string" ? value.message : "Не удалось создать пользователя."; }
export function AdminUserCreateForm() { const router = useRouter(); const [role, setRole] = useState<"USER" | "ADMIN">("USER"); const [permissions, setPermissions] = useState<readonly AuthPermission[]>([]); const [secret, setSecret] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null); try { const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ login: form.get("login"), role, permissions: role === "USER" ? permissions : [] }) }); const body: unknown = await response.json(); const result = response.ok ? parseOneTimePasswordResult(body) : null; if (!result) { setError(errorMessage(body)); return; } setSecret(result.temporaryPassword); } catch { setError("Не удалось создать пользователя."); } finally { setBusy(false); } } if (secret) return <OneTimePassword password={secret} title="Пользователь создан" onDone={() => { setSecret(null); router.push("/admin/users"); router.refresh(); }} />; return <form className="admin-form" onSubmit={submit} noValidate><label>Логин<input name="login" minLength={3} maxLength={64} pattern="[A-Za-z0-9._-]{3,64}" required autoComplete="off" /></label><label>Роль<select value={role} onChange={(event) => setRole(event.currentTarget.value as "USER" | "ADMIN")}><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select></label>{role === "USER" ? <PermissionSelector value={permissions} onChange={setPermissions} /> : <p className="admin-note">ADMIN получает полный доступ. Отдельные разрешения USER не используются.</p>}{error && <p role="alert">{error}</p>}<button type="submit" disabled={busy}>{busy ? "Создание…" : "Создать пользователя"}</button></form>; }
