"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import type { DashboardVehiclesResponse } from "@/lib/dashboard/dashboard-contract";
import { formatDistance, formatGeneratedAt, formatSpeed, formatTimestamp, freshnessLabel, qualityLabel, sourceLabel, statusLabel } from "@/lib/dashboard/dashboard-formatters";
import { dashboardHistoryPath, shouldUpdateDashboardHistory, type DashboardNavigationReason } from "@/lib/dashboard/dashboard-navigation";
import { parseDashboardQuery, serializeDashboardQuery, type DashboardActivity, type DashboardQuery, type DashboardStatus } from "@/lib/dashboard/dashboard-query";
import { SchedulerStatus } from "@/components/scheduler-status";
import { ClockIcon, FleetIcon, HelpIcon, HistoryIcon, NoPositionIcon, OfflineIcon, OnlineIcon, RouteIcon, WarningIcon } from "@/components/ui/icons";
import type { SchedulerStatusResponse } from "@/lib/scheduler/scheduler-contract";
import { useI18n } from "../i18n/client";

type Props = Readonly<{ initialData: DashboardVehiclesResponse; initialQuery: DashboardQuery; initialSchedulerStatus: SchedulerStatusResponse | null }>;
function statusTone(status: string): string { return status === "online" ? "badge badge-online" : status === "offline" ? "badge badge-offline" : "badge badge-unknown"; }
function freshnessTone(value: string): string { return value === "fresh" ? "badge badge-fresh" : value === "missing" ? "badge badge-missing" : "badge badge-stale"; }
function StatusIcon({ status }: Readonly<{ status: string }>) { const Icon = status === "online" ? OnlineIcon : status === "offline" ? OfflineIcon : HelpIcon; return <Icon className="status-icon" size={14} />; }
function FreshnessIcon({ value }: Readonly<{ value: string }>) { const Icon = value === "fresh" ? ClockIcon : value === "missing" ? NoPositionIcon : HistoryIcon; return <Icon className="status-icon" size={14} />; }

export function DashboardClient({ initialData, initialQuery, initialSchedulerStatus }: Props) {
  const { locale, t } = useI18n();
  const [data, setData] = useState(initialData); const [query, setQuery] = useState<DashboardQuery>(initialQuery); const [loading, setLoading] = useState(false); const [error, setError] = useState(false); const first = useRef(true); const controller = useRef<AbortController | null>(null);
  const request = useCallback(async (next: DashboardQuery, reason: DashboardNavigationReason) => {
    controller.current?.abort(); const abort = new AbortController(); controller.current = abort; setLoading(true); setError(false);
    const encoded = serializeDashboardQuery(next); if (shouldUpdateDashboardHistory(reason)) window.history.pushState(null, "", dashboardHistoryPath(next));
    try { const response = await fetch(`/api/dashboard/vehicles${encoded ? `?${encoded}` : ""}`, { signal: abort.signal, cache: "no-store" }); if (!response.ok) throw new Error(); const body = await response.json() as DashboardVehiclesResponse; if (!abort.signal.aborted) setData(body); }
    catch { if (!abort.signal.aborted) setError(true); }
    finally { if (!abort.signal.aborted) setLoading(false); }
  }, []);
  useEffect(() => { if (first.current) { first.current = false; return; } const timer = window.setTimeout(() => { void request(query, "user"); }, 300); return () => window.clearTimeout(timer); }, [query, request]);
  useEffect(() => { const onPopState = () => { const restored = parseDashboardQuery(new URLSearchParams(window.location.search)); first.current = true; setQuery(restored); void request(restored, "popstate"); }; window.addEventListener("popstate", onPopState); return () => { window.removeEventListener("popstate", onPopState); controller.current?.abort(); }; }, [request]);
  const set = <K extends keyof DashboardQuery>(key: K, value: DashboardQuery[K]) => setQuery((current) => ({ ...current, [key]: value }));
  const retry = () => void request(query, error ? "retry" : "refresh");
  return <>
    <Header data={data} />
    <SchedulerStatus initialStatus={initialSchedulerStatus} timezone={data.timezone || "Europe/Kyiv"} />
    <section className="filters" aria-label={t("dashboard.filters.label")}>
      <label>{t("dashboard.filters.search")}<input value={query.search ?? ""} onChange={(event) => set("search", event.target.value || undefined)} placeholder={t("dashboard.filters.searchPlaceholder")} /></label>
      <label>{t("dashboard.filters.status")}<select value={query.status ?? ""} onChange={(event) => set("status", (event.target.value || undefined) as DashboardStatus | undefined)}><option value="">{t("common.all")}</option><option value="online">{t("dashboard.status.online")}</option><option value="offline">{t("dashboard.status.offline")}</option><option value="unknown">{t("dashboard.status.unknown")}</option></select></label>
      <label>{t("dashboard.filters.activity")}<select value={query.activity ?? ""} onChange={(event) => set("activity", (event.target.value || undefined) as DashboardActivity | undefined)}><option value="">{t("common.all")}</option><option value="below_threshold">{t("dashboard.activity.belowThreshold")}</option><option value="normal">{t("dashboard.activity.normalDistance")}</option><option value="no_data">{t("dashboard.activity.noData")}</option></select></label>
      <label className="check"><input type="checkbox" checked={query.includeDisabled !== false} onChange={(event) => set("includeDisabled", event.target.checked)} /> {t("dashboard.filters.showDisabled")}</label>
      <button type="button" onClick={retry} disabled={loading}>{loading ? t("common.refreshing") : t("common.refresh")}</button>
    </section>
    {error && <section className="notice" role="alert"><WarningIcon className="notice-icon" /><div><strong>{t("dashboard.loadError")}</strong><button type="button" onClick={retry}>{t("common.retry")}</button></div></section>}
    {loading && <p className="refresh" aria-live="polite">{t("dashboard.refreshingData")}</p>}
    <Summary data={data} />
    {data.vehicles.length === 0 ? <section className="empty"><h2>{t("dashboard.emptyTitle")}</h2><p>{t("dashboard.emptyText")}</p></section> : <><div className="table-wrap"><table><thead><tr><th>{t("dashboard.table.vehicle")}</th><th>{t("dashboard.table.status")}</th><th>{t("dashboard.table.gps")}</th><th>{t("dashboard.table.currentSpeed")}</th><th>{t("dashboard.table.dailyDistance")}</th><th>{t("dashboard.table.sourceQuality")}</th><th>{t("dashboard.table.activity")}</th></tr></thead><tbody>{data.vehicles.map((vehicle) => <tr key={vehicle.id}><td><strong><Link className="vehicle-detail-link" href={`/vehicles/${vehicle.id}`}>{vehicle.name}</Link></strong>{vehicle.disabled && <span className="disabled">{t("dashboard.vehicle.disabled")}</span>}</td><td><span className={statusTone(vehicle.status)}><StatusIcon status={vehicle.status} />{statusLabel(vehicle.status, locale)}</span></td><td><span className={freshnessTone(vehicle.positionFreshness)}><FreshnessIcon value={vehicle.positionFreshness} />{freshnessLabel(vehicle.positionFreshness, locale)}</span><small>{formatTimestamp(vehicle.fixTime, data.timezone, locale)}</small></td><td>{formatSpeed(vehicle.speedKph, locale)}</td><td className={vehicle.belowMinimumDistance ? "below" : ""}>{formatDistance(vehicle.dailyDistanceMeters, locale)}</td><td><span>{sourceLabel(vehicle.dailyDistanceSource, locale)}</span><small>{qualityLabel(vehicle.dailyDistanceQuality, locale)}</small></td><td>{vehicle.belowMinimumDistance ? <span className="alert-label">{t("dashboard.activity.belowThreshold")}</span> : vehicle.dailyDistanceMeters === null ? t("common.noData") : t("dashboard.activity.normal")}</td></tr>)}</tbody></table></div><div className="mobile-list">{data.vehicles.map((vehicle) => <article className="vehicle-card" key={vehicle.id}><div><strong><Link className="vehicle-detail-link" href={`/vehicles/${vehicle.id}`}>{vehicle.name}</Link></strong>{vehicle.disabled && <span className="disabled">{t("dashboard.vehicle.disabled")}</span>}</div><div className="badges"><span className={statusTone(vehicle.status)}><StatusIcon status={vehicle.status} />{statusLabel(vehicle.status, locale)}</span><span className={freshnessTone(vehicle.positionFreshness)}><FreshnessIcon value={vehicle.positionFreshness} />{freshnessLabel(vehicle.positionFreshness, locale)}</span></div><dl><div><dt>{t("dashboard.mobile.speed")}</dt><dd>{formatSpeed(vehicle.speedKph, locale)}</dd></div><div><dt>{t("dashboard.mobile.distance")}</dt><dd className={vehicle.belowMinimumDistance ? "below" : ""}>{formatDistance(vehicle.dailyDistanceMeters, locale)}</dd></div><div><dt>{t("dashboard.mobile.data")}</dt><dd>{qualityLabel(vehicle.dailyDistanceQuality, locale)}</dd></div></dl>{vehicle.belowMinimumDistance && <p className="alert-label alert-label-with-icon"><WarningIcon size={16} />{t("dashboard.activity.distanceBelow")}</p>}</article>)}</div></>}
  </>;
}

function Summary({ data }: Readonly<{ data: DashboardVehiclesResponse }>) { const { t } = useI18n(); const cards = [[t("dashboard.summary.total"), data.summary.total, FleetIcon], [t("dashboard.summary.online"), data.summary.online, OnlineIcon], [t("dashboard.summary.offline"), data.summary.offline, OfflineIcon], [t("dashboard.summary.unknown"), data.summary.unknown, HelpIcon], [t("dashboard.summary.fresh"), data.summary.freshPositions, ClockIcon], [t("dashboard.summary.stale"), data.summary.stalePositions, HistoryIcon], [t("dashboard.summary.missing"), data.summary.withoutPosition, NoPositionIcon], [t("dashboard.summary.belowMinimum"), data.summary.belowMinimumDistance, WarningIcon], [t("dashboard.summary.withoutDistance"), data.summary.withoutDailyStat, RouteIcon]] as const; return <section className="summary-grid" aria-label={t("dashboard.summary.label")}>{cards.map(([label, value, Icon]) => <article className="summary-card" key={label}><span className="summary-card-icon"><Icon size={18} /></span><div><p>{label}</p><strong>{value}</strong></div></article>)}</section>; }
function Header({ data }: Readonly<{ data: DashboardVehiclesResponse }>) { const { locale, t } = useI18n(); return <header className="hero"><p className="eyebrow">{t("dashboard.eyebrow")}</p><h1>{t("dashboard.title")}</h1><p>{t("dashboard.description")}</p><div className="metadata"><span>{t("dashboard.metadata.serviceDate")} <strong>{data.serviceDate}</strong></span><span>{t("dashboard.metadata.timezone")} <strong>{data.timezone}</strong></span><span>{t("dashboard.metadata.vehicles")} <strong>{data.summary.total}</strong></span><span>{t("dashboard.metadata.generated")} <time dateTime={data.generatedAt}>{formatGeneratedAt(data.generatedAt, data.timezone, locale)}</time></span></div></header>; }
