"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import * as maplibregl from "maplibre-gl";
import type { GeoJSONSource, Map as MapLibreMap } from "maplibre-gl";
import { fleetMapInitialCamera } from "@/lib/fleet-map/fleet-map-camera";
import { initialFleetMapBasemapState, recordFleetMapBasemapError, recordFleetMapBasemapLoad } from "@/lib/fleet-map/fleet-map-basemap-state";
import { parseFleetMapResponse, type FleetMapResponse, type FleetMapVehicle } from "@/lib/fleet-map/fleet-map-contract";
import { formatFleetMapAge, formatFleetMapTimestamp } from "@/lib/fleet-map/fleet-map-formatters";
import { fleetMapToGeoJson } from "@/lib/fleet-map/fleet-map-geojson";
import { reconcileFleetMapSelection, selectedFleetMapVehicle } from "@/lib/fleet-map/fleet-map-selection";
import { fleetMapStyleUrl } from "@/lib/fleet-map/fleet-map-style";
import { createFleetMapAfterWorkerBootstrap, type FleetMapWorkerBootstrapState } from "@/lib/fleet-map/fleet-map-worker-bootstrap";

const SOURCE_ID = "fleet-vehicles"; const LAYER_ID = "fleet-vehicles"; const SELECTED_LAYER_ID = "fleet-vehicles-selected";
const MAPLIBRE_WORKER_URL = "/maplibre/maplibre-gl-worker.mjs";
const mapLibreWorkerBootstrapState: FleetMapWorkerBootstrapState = { configured: false };
type Props = Readonly<{ initialSnapshot: FleetMapResponse }>;
function updateMapData(map: MapLibreMap, snapshot: FleetMapResponse, selectedId: string | null): void { const source = map.getSource(SOURCE_ID) as GeoJSONSource | undefined; if (!source) return; source.setData(fleetMapToGeoJson(snapshot)); map.setFilter(SELECTED_LAYER_ID, ["==", ["get", "vehicleId"], selectedId ?? "__none__"]); }
function applyInitialCamera(map: MapLibreMap, snapshot: FleetMapResponse): void { const camera = fleetMapInitialCamera(snapshot); if ("bounds" in camera) map.fitBounds(camera.bounds as [[number, number], [number, number]], { padding: camera.padding, maxZoom: camera.maxZoom, duration: 0 }); else map.jumpTo({ center: camera.center as [number, number], zoom: camera.zoom }); }
function freshnessLabel(value: "FRESH" | "STALE"): string { return value === "FRESH" ? "Свежая позиция" : "Устаревшая позиция"; }
function formatSpeed(value: number | null): string { return value === null ? "—" : `${value.toFixed(1)} км/ч`; }

export function FleetMapClient({ initialSnapshot }: Props) {
  const [snapshot, setSnapshot] = useState(initialSnapshot); const [selectedId, setSelectedId] = useState<string | null>(null); const [refreshing, setRefreshing] = useState(false); const [refreshError, setRefreshError] = useState(false); const [styleError, setStyleError] = useState(false);
  const containerRef = useRef<HTMLDivElement | null>(null); const mapRef = useRef<MapLibreMap | null>(null); const snapshotRef = useRef(snapshot); const selectedRef = useRef(selectedId); const basemapStateRef = useRef(initialFleetMapBasemapState()); const initialFitRef = useRef(false); const activeRequestRef = useRef(false); const controllerRef = useRef<AbortController | null>(null); const generationRef = useRef(0);
  const refresh = useCallback(async (): Promise<void> => { if (activeRequestRef.current) return; activeRequestRef.current = true; const generation = ++generationRef.current; const controller = new AbortController(); controllerRef.current = controller; setRefreshing(true); try { const response = await fetch("/api/fleet/map", { cache: "no-store", signal: controller.signal, headers: { Accept: "application/json" } }); if (!response.ok) throw new Error("Fleet map refresh failed."); const next = parseFleetMapResponse(await response.json()); if (!controller.signal.aborted && generation === generationRef.current) { setSnapshot(next); setSelectedId((current) => reconcileFleetMapSelection(next, current)); setRefreshError(false); } } catch { if (!controller.signal.aborted && generation === generationRef.current) setRefreshError(true); } finally { if (generation === generationRef.current) { activeRequestRef.current = false; setRefreshing(false); } } }, []);
  useEffect(() => { const container = containerRef.current; if (!container || mapRef.current) return; const map = createFleetMapAfterWorkerBootstrap({ setWorkerUrl: maplibregl.setWorkerUrl, workerUrl: MAPLIBRE_WORKER_URL, state: mapLibreWorkerBootstrapState }, () => new maplibregl.Map({ container, style: fleetMapStyleUrl(), pitchWithRotate: false, dragRotate: false })); mapRef.current = map; map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-right"); const onLoad = () => { basemapStateRef.current = recordFleetMapBasemapLoad(); setStyleError(false); map.addSource(SOURCE_ID, { type: "geojson", data: fleetMapToGeoJson(snapshotRef.current) }); map.addLayer({ id: LAYER_ID, type: "circle", source: SOURCE_ID, paint: { "circle-radius": 7, "circle-color": ["match", ["get", "freshness"], "FRESH", "#17734d", "#9a6110"], "circle-opacity": ["match", ["get", "freshness"], "FRESH", 0.95, 0.72], "circle-stroke-width": 2, "circle-stroke-color": "#ffffff" } }); map.addLayer({ id: SELECTED_LAYER_ID, type: "circle", source: SOURCE_ID, filter: ["==", ["get", "vehicleId"], selectedRef.current ?? "__none__"], paint: { "circle-radius": 12, "circle-color": "#1d5f87", "circle-opacity": 0.3, "circle-stroke-width": 3, "circle-stroke-color": "#1d5f87" } }); updateMapData(map, snapshotRef.current, selectedRef.current); if (!initialFitRef.current) { initialFitRef.current = true; applyInitialCamera(map, snapshotRef.current); } }; const onClick = (event: maplibregl.MapLayerMouseEvent) => { const vehicleId = event.features?.[0]?.properties?.vehicleId; if (typeof vehicleId === "string") setSelectedId(vehicleId); }; const onError = () => { basemapStateRef.current = recordFleetMapBasemapError(basemapStateRef.current); setStyleError(basemapStateRef.current.error); }; map.on("load", onLoad); map.on("click", LAYER_ID, onClick); map.on("error", onError); return () => { map.off("load", onLoad); map.off("click", LAYER_ID, onClick); map.off("error", onError); map.remove(); mapRef.current = null; }; }, []);
  useEffect(() => { snapshotRef.current = snapshot; selectedRef.current = selectedId; const map = mapRef.current; if (map && map.isStyleLoaded()) updateMapData(map, snapshot, selectedId); }, [snapshot, selectedId]);
  useEffect(() => { let cancelled = false; let timer: number | undefined; const schedule = () => { timer = window.setTimeout(async () => { await refresh(); if (!cancelled) schedule(); }, 30_000); }; schedule(); return () => { cancelled = true; if (timer !== undefined) window.clearTimeout(timer); generationRef.current += 1; controllerRef.current?.abort(); activeRequestRef.current = false; }; }, [refresh]);
  const selected = selectedFleetMapVehicle(snapshot, selectedId);
  return <><header className="hero"><p className="eyebrow">Текущий snapshot автопарка</p><h1>Карта</h1><p>Позиции автомобилей из локального persisted состояния.</p><div className="metadata"><span>Сформировано: <strong>{formatFleetMapTimestamp(snapshot.generatedAt)}</strong></span><span>Порог свежести: <strong>{snapshot.positionFreshnessSeconds} сек</strong></span></div></header><section className="map-summary" aria-label="Сводка карты"><Summary snapshot={snapshot} /><button type="button" onClick={() => void refresh()} disabled={refreshing}>{refreshing ? "Обновление…" : "Обновить"}</button></section><div className="map-legend" aria-label="Легенда"><span><i className="map-dot map-dot-fresh" />Свежая позиция</span><span><i className="map-dot map-dot-stale" />Устаревшая позиция</span></div>{refreshing && <p className="refresh" aria-live="polite">Обновление данных карты…</p>}{refreshError && <section className="notice" role="alert"><span>⚠</span><div><strong>Не удалось обновить карту</strong><span>Показан последний успешный snapshot.</span></div></section>}{styleError && <section className="notice" role="alert"><span>⚠</span><div><strong>Не удалось загрузить базовую карту</strong><span>Данные автопарка доступны, повторите попытку позже.</span></div></section>}<section className="map-shell" aria-label="Интерактивная карта автопарка"><div ref={containerRef} className="fleet-map-canvas" data-fleet-map-container="true" />{snapshot.summary.withPosition === 0 && <div className="map-empty">Нет автомобилей с доступной позицией.</div>}</section><SelectedVehicle vehicle={selected} generatedAt={snapshot.generatedAt} /></>;
}
function Summary({ snapshot }: Readonly<{ snapshot: FleetMapResponse }>) { const values = [["Всего автомобилей", snapshot.summary.totalVehicles], ["На карте", snapshot.summary.withPosition], ["Свежие", snapshot.summary.fresh], ["Устаревшие", snapshot.summary.stale], ["Без позиции", snapshot.summary.withoutPosition]] as const; return <>{values.map(([label, value]) => <article className="map-summary-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}{snapshot.summary.invalidPosition > 0 && <p className="map-warning">Некорректных позиций: {snapshot.summary.invalidPosition}</p>}</>; }
function SelectedVehicle({ vehicle, generatedAt }: Readonly<{ vehicle: FleetMapVehicle | null; generatedAt: string }>) { if (!vehicle) return <section className="map-details" aria-live="polite"><h2>Автомобиль не выбран</h2><p>Выберите точку на карте, чтобы увидеть её состояние.</p></section>; return <section className="map-details" aria-live="polite"><h2>{vehicle.vehicle.name}</h2><dl><div><dt>Состояние</dt><dd>{freshnessLabel(vehicle.freshness)}</dd></div><div><dt>Скорость</dt><dd>{formatSpeed(vehicle.speedKph)}</dd></div><div><dt>Время позиции</dt><dd>{formatFleetMapTimestamp(vehicle.position.observedAt)}</dd></div><div><dt>Возраст</dt><dd>{formatFleetMapAge(vehicle.position.observedAt, generatedAt)}</dd></div></dl></section>; }
