"use client";

import { useI18n } from "../i18n/client";
import { formatDateTime, formatNumber, formatUnit } from "../i18n/formatting";
import type { PositionHistoryStatusResponse } from "../lib/position-history-status/position-history-status-contract";
import type { SafeDurableRun } from "../lib/position-history-durable-runs/position-history-durable-run-contract";
import { PositionHistoryPopulation } from "./position-history-population";
import { PositionHistoryDurableRuns } from "./position-history-durable-runs";

type Props = Readonly<{ anchor: string | null; data: PositionHistoryStatusResponse | null; error: "INVALID_ANCHOR" | "UNAVAILABLE" | null; canPopulate?: boolean; showDurableRuns?: boolean; initialDurableActive?: SafeDurableRun | null; initialDurableRecent?: readonly SafeDurableRun[] }>;

export function PositionHistoryStatusView({ anchor, data, error, canPopulate = false, showDurableRuns = false, initialDurableActive = null, initialDurableRecent = [] }: Props) {
  const { locale, t } = useI18n();
  const newestFirst = data ? [...data.sliceStatuses].reverse() : [];
  const number = (value: number) => formatNumber(locale, value);
  const instant = (value: string | null) => value === null ? t("history.observations.none") : (formatDateTime(locale, value) ?? t("common.notAvailable"));

  return <>
    <header className="hero admin-history-hero"><p className="eyebrow">{t("history.eyebrow")}</p><h1>{t("history.title")}</h1><p>{t("history.description")}</p></header>
    <section className="admin-history-controls" aria-labelledby="policy-anchor-title"><h2 id="policy-anchor-title">{t("history.policy.title")}</h2><p><strong>{t("history.policy.days", { days: formatUnit(locale, data?.policyDays ?? 90, "day") })}</strong></p><p>{t("history.policy.architecture")}</p><form action="/admin/history" method="get"><label>{t("history.anchor.label")}<input name="to" defaultValue={anchor ?? ""} placeholder="2026-08-11T02:00:00.000Z" /></label><button type="submit">{t("history.anchor.recalculate")}</button></form><p>{t("history.anchor.help")}</p></section>
    {error === "INVALID_ANCHOR" && <section className="notice" role="alert"><span>⚠</span><div><strong>{t("history.anchor.invalidTitle")}</strong><span>{t("history.anchor.invalidText")}</span></div></section>}
    {error === "UNAVAILABLE" && <section className="notice" role="alert"><span>⚠</span><div><strong>{t("history.unavailableTitle")}</strong><span>{t("history.unavailableText")}</span></div></section>}
    {data && <>
      <section className="admin-history-section"><h2>{t("history.policy.title")}</h2><div className="admin-history-summary"><article><span>{t("history.summary.from")}</span><strong>{data.from}</strong></article><article><span>{t("history.summary.to")}</span><strong>{data.to}</strong></article><article><span>{t("history.summary.ranges")}</span><strong>{number(data.slices.total)}</strong></article><article><span>{t("history.summary.fullSeven")}</span><strong>{number(data.slices.fullSevenDay)}</strong></article><article><span>{t("history.summary.remainder")}</span><strong>{data.slices.remainderHours === null ? t("common.noData") : formatUnit(locale, data.slices.remainderHours, "hour")}</strong></article></div></section>
      <section className="admin-history-section"><h2>{t("history.backfill.title")}</h2><p className="admin-history-disclaimer">{t("history.backfill.disclaimer")}</p><div className="admin-history-summary"><article><span>{t("history.backfill.fleetTotal")}</span><strong>{number(data.fleet.total)}</strong></article><article><span>{t("history.backfill.eligible")}</span><strong>{number(data.fleet.providerEligible)}</strong></article><article><span>{t("history.backfill.disabled")}</span><strong>{number(data.fleet.providerDisabled)}</strong></article><article><span>{t("history.backfill.completed")}</span><strong>{number(data.backfill.completedPairs)} / {number(data.backfill.targetVehiclePairs)}</strong></article><article><span>{t("history.backfill.remaining")}</span><strong>{number(data.backfill.incompletePairs)}</strong></article><article><span>{t("history.backfill.eligibleRemaining")}</span><strong>{number(data.backfill.providerEligibleIncompletePairs)}</strong></article><article><span>{t("history.backfill.hourlyRemaining")}</span><strong>{number(data.backfill.estimatedRemainingHourlyWindows)}</strong></article></div><div className="admin-history-progress" aria-label={t("history.backfill.progressLabel")}><progress max={data.backfill.targetVehiclePairs || 1} value={data.backfill.completedPairs} /><span>{t("history.backfill.progress", { done: number(data.backfill.completedPairs), total: number(data.backfill.targetVehiclePairs) })}</span></div><p className="admin-history-disclaimer">{t("history.backfill.disabledHelp")}</p></section>
      <section className="admin-history-section"><h2>{t("history.observations.title")}</h2><p className="admin-history-disclaimer">{t("history.observations.disclaimer")}</p><div className="admin-history-summary"><article><span>{t("history.observations.rows")}</span><strong>{number(data.observations.rowCount)}</strong></article><article><span>{t("history.observations.with")}</span><strong>{number(data.observations.vehiclesWithObservations)}</strong></article><article><span>{t("history.observations.without")}</span><strong>{number(data.observations.vehiclesWithoutObservations)}</strong></article><article><span>{t("history.observations.first")}</span><strong>{instant(data.observations.firstObservationAt)}</strong></article><article><span>{t("history.observations.last")}</span><strong>{instant(data.observations.lastObservationAt)}</strong></article></div></section>
      <section className="admin-history-section"><h2>{t("history.slices.title")}</h2><p className="admin-history-disclaimer">{t("history.slices.disclaimer")}</p><div className="admin-history-table-wrap"><table className="admin-history-table"><thead><tr><th>{t("history.slices.from")}</th><th>{t("history.slices.to")}</th><th>{t("history.slices.duration")}</th><th>COMPLETED</th><th>RUNNING</th><th>PENDING</th><th>NONE</th><th>{t("history.backfill.eligibleRemaining")}</th><th>{t("history.backfill.hourlyRemaining")}</th></tr></thead><tbody>{newestFirst.map((slice) => <tr key={`${slice.from}/${slice.to}`}><td>{slice.from}</td><td>{slice.to}</td><td>{formatUnit(locale, slice.durationHours, "hour")}</td><td>{number(slice.completed)} / {number(slice.vehiclesTotal)}</td><td>{number(slice.running)}</td><td>{number(slice.pending)}</td><td>{number(slice.none)}</td><td>{number(slice.providerEligibleRemaining)}</td><td>{number(slice.estimatedRemainingHourlyWindows)}</td></tr>)}</tbody></table></div></section>
      {anchor && canPopulate && <PositionHistoryPopulation anchor={anchor} />}
      <aside className="admin-history-help"><strong>{t("history.operations.title")}</strong><p>{t("history.operations.text")}</p></aside>
    </>}
    {anchor && showDurableRuns && <PositionHistoryDurableRuns key={`${anchor}:${initialDurableActive?.id ?? "none"}:${initialDurableActive?.committedWindows ?? 0}:${initialDurableRecent[0]?.id ?? "none"}`} anchor={anchor} canPopulate={canPopulate} initialActive={initialDurableActive} initialRecent={initialDurableRecent} />}
  </>;
}
