import type { PositionHistoryStatusResponse } from "@/lib/position-history-status/position-history-status-contract";
import { PositionHistoryPopulation } from "./position-history-population";

type Props = Readonly<{ anchor: string | null; data: PositionHistoryStatusResponse | null; error: "INVALID_ANCHOR" | "UNAVAILABLE" | null; canPopulate?: boolean }>;
function formatInstant(value: string | null): string { return value ?? "Нет наблюдений"; }
function formatHours(value: number | null): string { return value === null ? "Нет" : `${value} ч`; }

export function PositionHistoryStatusView({ anchor, data, error, canPopulate = false }: Props) {
  const newestFirst = data ? [...data.sliceStatuses].reverse() : [];
  return <>
    <header className="hero admin-history-hero"><p className="eyebrow">Администрирование</p><h1>История GPS</h1><p>План на контрольную точку: состояние точных целей исторического заполнения, а не полнота GPS-данных.</p></header>
    <section className="admin-history-controls" aria-labelledby="policy-anchor-title"><h2 id="policy-anchor-title">Политика и контрольная точка</h2><p><strong>История GPS: {data?.policyDays ?? 90} дней</strong></p><p>Архитектура рассчитана на последующее расширение периода хранения.</p><form action="/admin/history" method="get"><label>Контрольная точка (абсолютный ISO, Z или смещение)<input name="to" defaultValue={anchor ?? ""} placeholder="2026-08-11T02:00:00.000Z" /></label><button type="submit">Пересчитать статус</button></form><p>Изменение контрольной точки пересчитывает точный план и сопоставление чекпоинтов. Оно не перемещает и не удаляет данные.</p></section>
    {error === "INVALID_ANCHOR" && <section className="notice" role="alert"><span>⚠</span><div><strong>Некорректная контрольная точка</strong><span>Укажите полный абсолютный timestamp с Z или числовым смещением. Запрос к backend не отправлен.</span></div></section>}
    {error === "UNAVAILABLE" && <section className="notice" role="alert"><span>⚠</span><div><strong>Не удалось загрузить статус</strong><span>Контрольная точка сохранена в URL. Повторите загрузку позднее.</span></div></section>}
    {data && <>
      <section className="admin-history-section"><h2>Политика и контрольная точка</h2><div className="admin-history-summary"><article><span>Горизонт с</span><strong>{data.from}</strong></article><article><span>Горизонт до / контрольная точка</span><strong>{data.to}</strong></article><article><span>Диапазонов</span><strong>{data.slices.total}</strong></article><article><span>Полных 7-дневных</span><strong>{data.slices.fullSevenDay}</strong></article><article><span>Остаток</span><strong>{formatHours(data.slices.remainderHours)}</strong></article></div></section>
      <section className="admin-history-section"><h2>Заполнение истории</h2><p className="admin-history-disclaimer">COMPLETED означает, что принятая цель backfill обработана. Это не доказывает наличие, плотность или полноту GPS-наблюдений.</p><div className="admin-history-summary"><article><span>Машин всего</span><strong>{data.fleet.total}</strong></article><article><span>Доступны у провайдера</span><strong>{data.fleet.providerEligible}</strong></article><article><span>Provider-disabled</span><strong>{data.fleet.providerDisabled}</strong></article><article><span>Целей обработано</span><strong>{data.backfill.completedPairs} / {data.backfill.targetVehiclePairs}</strong></article><article><span>Осталось целей</span><strong>{data.backfill.incompletePairs}</strong></article><article><span>Доступных целей осталось</span><strong>{data.backfill.providerEligibleIncompletePairs}</strong></article><article><span>Осталось часовых окон</span><strong>{data.backfill.estimatedRemainingHourlyWindows}</strong></article></div><div className="admin-history-progress" aria-label="Завершение целей backfill"><progress max={data.backfill.targetVehiclePairs || 1} value={data.backfill.completedPairs} /><span>{data.backfill.completedPairs} из {data.backfill.targetVehiclePairs} целей обработано</span></div><p className="admin-history-disclaimer">Provider-disabled — техническое состояние у провайдера; оно не означает, что машина выключена из бизнеса или автопарка. Такие машины остаются в общей правде чекпоинтов.</p></section>
      <section className="admin-history-section"><h2>GPS-наблюдения</h2><p className="admin-history-disclaimer">Отдельные факты сохранённых наблюдений в выбранном горизонте. Они не определяют статус чекпоинтов и не образуют процент полноты.</p><div className="admin-history-summary"><article><span>Строк наблюдений</span><strong>{data.observations.rowCount}</strong></article><article><span>Машин с наблюдениями</span><strong>{data.observations.vehiclesWithObservations}</strong></article><article><span>Машин без наблюдений</span><strong>{data.observations.vehiclesWithoutObservations}</strong></article><article><span>Первое наблюдение</span><strong>{formatInstant(data.observations.firstObservationAt)}</strong></article><article><span>Последнее наблюдение</span><strong>{formatInstant(data.observations.lastObservationAt)}</strong></article></div></section>
      <section className="admin-history-section"><h2>Диапазоны заполнения</h2><p className="admin-history-disclaimer">От новых к старым. RUNNING и PENDING остаются незавершёнными; продвижение RUNNING отражено только в оставшихся часовых окнах.</p><div className="admin-history-table-wrap"><table className="admin-history-table"><thead><tr><th>С</th><th>До</th><th>Длительность</th><th>COMPLETED</th><th>RUNNING</th><th>PENDING</th><th>NONE</th><th>Доступных осталось</th><th>Часовых окон осталось</th></tr></thead><tbody>{newestFirst.map((slice) => <tr key={`${slice.from}/${slice.to}`}><td>{slice.from}</td><td>{slice.to}</td><td>{slice.durationHours} ч</td><td>{slice.completed} / {slice.vehiclesTotal}</td><td>{slice.running}</td><td>{slice.pending}</td><td>{slice.none}</td><td>{slice.providerEligibleRemaining}</td><td>{slice.estimatedRemainingHourlyWindows}</td></tr>)}</tbody></table></div></section>
      {anchor && canPopulate && <PositionHistoryPopulation anchor={anchor} />}
      <aside className="admin-history-help"><strong>Операционный режим</strong><p>Браузерный запуск ограничен 24 часовыми окнами. Для большого контролируемого дозаполнения используется CLI-команда <code>position-history:horizon-populate</code>.</p></aside>
    </>}
  </>;
}
