"use client";
import { useState } from "react";
import { useI18n } from "@/i18n/client";
import { Alert, AlertDialog, Button, Badge } from "@/components/ui";
type State = "NOT_CONNECTED" | "LINK_PENDING" | "CONNECTED" | "BROKEN";
export function TelegramNotificationsPanel({ initial }: Readonly<{ initial: Readonly<{ status: State; pendingExpiresAt: string | null }> }>) {
  const { t } = useI18n(); const [state, setState] = useState(initial); const [url, setUrl] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<"generic" | "rate" | "disabled" | null>(null); const [confirmDisconnect, setConfirmDisconnect] = useState(false);
  const connected = state.status === "CONNECTED"; const recoverable = connected || state.status === "BROKEN";
  async function connect(): Promise<void> { setBusy(true); setError(null); try { const r = await fetch("/api/account/notifications/telegram/link", { method: "POST" }); const value: unknown = await r.json().catch(() => null); if (r.status === 429) { setError("rate"); return; } if (r.status === 409) { setError("disabled"); return; } if (!r.ok || typeof value !== "object" || value === null || typeof (value as Record<string, unknown>).telegramUrl !== "string" || typeof (value as Record<string, unknown>).expiresAt !== "string") throw new Error(); const result = value as { telegramUrl: string; expiresAt: string }; if (!/^https:\/\/t\.me\/[A-Za-z0-9_]+\?start=[A-Za-z0-9_-]{43}$/.test(result.telegramUrl)) throw new Error(); setUrl(result.telegramUrl); setState({ status: "LINK_PENDING", pendingExpiresAt: result.expiresAt }); } catch { setError("generic"); } finally { setBusy(false); } }
  async function disconnect(): Promise<void> { setBusy(true); setError(null); try { const r = await fetch("/api/account/notifications/telegram/disconnect", { method: "POST" }); const value: unknown = await r.json().catch(() => null); if (!r.ok || typeof value !== "object" || value === null || (value as Record<string, unknown>).status !== "NOT_CONNECTED") throw new Error(); setUrl(null); setState({ status: "NOT_CONNECTED", pendingExpiresAt: null }); setConfirmDisconnect(false); } catch { setError("generic"); } finally { setBusy(false); } }
  const expiry = state.pendingExpiresAt ? new Date(state.pendingExpiresAt) : null;
  return <section className="details-section" aria-busy={busy}><h2>{t("telegram.title")}</h2><Badge variant={state.status === "CONNECTED" ? "success" : state.status === "BROKEN" ? "warning" : "info"}>{t(`telegram.label.${state.status}`)}</Badge><p role="status" aria-live="polite">{t(`telegram.state.${state.status}`)}</p>{state.status === "LINK_PENDING" && !url ? <Alert variant="info" live="polite" title={t("telegram.pendingReload")} /> : null}{state.status === "BROKEN" ? <Alert variant="warning" live="polite" title={t("telegram.brokenHelp")} /> : null}{expiry ? <p>{t("telegram.expires", { expiresAt: expiry.toLocaleString() })}</p> : null}{url ? <Alert variant="info" title={t("telegram.linkReady")}><a className="admin-primary-link" href={url} target="_blank" rel="noopener noreferrer" aria-label={t("telegram.open")}>{t("telegram.open")}</a></Alert> : null}<div className="account-actions">{!recoverable && <Button disabled={busy || error === "disabled"} loading={busy} onClick={() => void connect()}>{state.status === "LINK_PENDING" ? t("telegram.regenerate") : t("telegram.connect")}</Button>}{recoverable && <Button disabled={busy || error === "disabled"} loading={busy} onClick={() => void connect()}>{t("telegram.reconnect")}</Button>}{recoverable && <AlertDialog open={confirmDisconnect} onOpenChange={setConfirmDisconnect} trigger={<Button variant="destructive" disabled={busy}>{t("telegram.disconnect")}</Button>} title={t("telegram.disconnectConfirmTitle")} description={t("telegram.disconnectConfirmBody")} cancelLabel={t("common.cancel")} confirmLabel={t("telegram.disconnect")} destructive loading={busy} onConfirm={() => void disconnect()} />}</div>{error ? <Alert variant={error === "generic" ? "danger" : "warning"} live="assertive" title={t(`telegram.error.${error}`)} /> : null}<p className="admin-note">{t("telegram.noPreferences")}</p></section>;
}
