"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import type { VehicleDetailsResponse } from "@/lib/vehicle-details/vehicle-details-contract";
import { parseVehicleDetailsResponse } from "@/lib/vehicle-details/vehicle-details-contract";
import { alertStatusLabel, alertTypeLabel, formatVehicleAge, formatVehicleDistance, formatVehicleDuration, formatVehicleSpeed, formatVehicleTimestamp, freshnessLabel, notificationDeliveryLabel, qualityLabel, sourceLabel, vehicleEventDetailsLabel } from "@/lib/vehicle-details/vehicle-details-formatters";
import { beginVehicleDetailsRefresh, failVehicleDetailsRefresh, initialVehicleDetailsRequestState, succeedVehicleDetailsRefresh } from "@/lib/vehicle-details/vehicle-details-request-state";

function alertTone(status: string): string { return status === "OPEN" ? "badge badge-alert-open" : "badge badge-alert-resolved"; }
function deliveryTone(status: string): string { return status === "SENT" ? "badge badge-delivery-sent" : status === "FAILED" ? "badge badge-delivery-failed" : status === "PENDING" ? "badge badge-delivery-pending" : "badge badge-delivery-none"; }
export function VehicleDetailsClient({ initialData }: Readonly<{ initialData: VehicleDetailsResponse }>) {
  const [state, setState] = useState(() => initialVehicleDetailsRequestState(initialData)); const stateRef = useRef(state); const active = useRef(false); const controller = useRef<AbortController | null>(null);
  useEffect(() => { stateRef.current = state; }, [state]);
  const refresh = useCallback(async () => { if (active.current) return; const begun = beginVehicleDetailsRefresh(stateRef.current); if (begun === stateRef.current) return; stateRef.current = begun; active.current = true; setState(begun); const generation = begun.generation; const nextController = new AbortController(); controller.current = nextController; try { const response = await fetch(`/api/vehicles/${begun.data.vehicle.id}/details`, { cache: "no-store", signal: nextController.signal, headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(); const data = parseVehicleDetailsResponse(await response.json()); if (!nextController.signal.aborted) { const next = succeedVehicleDetailsRefresh(stateRef.current, generation, data); stateRef.current = next; setState(next); } } catch { if (!nextController.signal.aborted) { const next = failVehicleDetailsRefresh(stateRef.current, generation); stateRef.current = next; setState(next); } } finally { if (generation === stateRef.current.generation) active.current = false; } }, []);
  useEffect(() => { const timer = window.setInterval(() => void refresh(), 30_000); return () => { window.clearInterval(timer); controller.current?.abort(); active.current = false; }; }, [refresh]);
  const { data } = state;
  return <>
    <header className="hero vehicle-details-hero"><p className="eyebrow">Карточка автомобиля</p><h1>{data.vehicle.name}</h1><div className="metadata"><span>Данные сформированы: <strong>{formatVehicleTimestamp(data.generatedAt)}</strong></span><Link href="/map">Открыть на карте</Link><Link href={`/vehicles/${data.vehicle.id}/trips`}>Поездки</Link><Link href={`/vehicles/${data.vehicle.id}/track`}>История движения</Link></div></header>
    <div className="vehicle-details-actions"><button type="button" onClick={() => void refresh()} disabled={state.loading}>{state.loading ? "Обновление…" : "Обновить"}</button>{state.loading && <span aria-live="polite">Обновление данных…</span>}</div>
    {state.refreshError && <section className="notice" role="alert"><span>⚠</span><div><strong>Не удалось обновить карточку</strong><span>Показаны последние успешно полученные данные.</span></div></section>}
    <div className="vehicle-details-grid">
      <section className="details-section"><h2>Текущее состояние</h2>{data.currentState === null ? <p className="details-empty">Текущая позиция недоступна</p> : <dl className="details-list"><div><dt>Статус позиции</dt><dd><span className={data.currentState.freshness === "FRESH" ? "badge badge-fresh" : "badge badge-stale"}>{freshnessLabel(data.currentState.freshness)}</span></dd></div><div><dt>Скорость</dt><dd>{formatVehicleSpeed(data.currentState.speedKph)}</dd></div><div><dt>Время позиции</dt><dd><time dateTime={data.currentState.position.observedAt}>{formatVehicleTimestamp(data.currentState.position.observedAt)}</time></dd></div><div><dt>Возраст</dt><dd>{formatVehicleAge(data.currentState.position.observedAt, data.generatedAt)}</dd></div></dl>}</section>
      <section className="details-section"><h2>Сегодня</h2>{data.today === null ? <p className="details-empty">Статистика за сегодня пока недоступна</p> : <><dl className="details-list"><div><dt>Пробег сегодня</dt><dd>{formatVehicleDistance(data.today.distanceMeters)}</dd></div><div><dt>Время движения</dt><dd>{formatVehicleDuration(data.today.movementDurationSeconds)}</dd></div><div><dt>Максимальная скорость</dt><dd>{formatVehicleSpeed(data.today.maxSpeedKph)}</dd></div><div><dt>Качество</dt><dd>{qualityLabel(data.today.quality)}</dd></div></dl><p className="details-secondary">Источник: {sourceLabel(data.today.source)}</p>{data.today.isStale && <p className="details-warning">Статистика может быть устаревшей.</p>}{data.today.isDegraded && <p className="details-warning">Статистика получена с неполными данными.</p>}</>}</section>
      <section className="details-section"><h2>Активные события</h2>{data.activeAlerts.length === 0 ? <p className="details-empty">Активных событий нет</p> : <ul className="details-events">{data.activeAlerts.map((alert) => <li key={alert.type}><strong>{alertTypeLabel(alert.type)}</strong><time dateTime={alert.openedAt}>Открыто: {formatVehicleTimestamp(alert.openedAt)}</time></li>)}</ul>}</section>
      <section className="details-section details-recent"><h2>Последние события</h2>{data.recentEvents.length === 0 ? <p className="details-empty">Последних событий нет</p> : <ul className="details-events">{data.recentEvents.map((event) => <li key={event.id}><div className="details-event-heading"><strong>{alertTypeLabel(event.type)}</strong><span className={alertTone(event.status)}>{alertStatusLabel(event.status)}</span><span className={deliveryTone(event.notificationDeliveryStatus)}>{notificationDeliveryLabel(event.notificationDeliveryStatus)}</span></div><span>Открыто: <time dateTime={event.openedAt}>{formatVehicleTimestamp(event.openedAt)}</time></span>{event.resolvedAt && <span>Завершено: <time dateTime={event.resolvedAt}>{formatVehicleTimestamp(event.resolvedAt)}</time></span>}<small>{vehicleEventDetailsLabel(event)}</small></li>)}</ul>}</section>
    </div>
  </>;
}
