"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import type { VehicleDetailsResponse } from "@/lib/vehicle-details/vehicle-details-contract";
import { parseVehicleDetailsResponse } from "@/lib/vehicle-details/vehicle-details-contract";
import { alertStatusLabel, alertTypeLabel, formatVehicleAge, formatVehicleDistance, formatVehicleDuration, formatVehicleSpeed, formatVehicleTimestamp, freshnessLabel, notificationDeliveryLabel, qualityLabel, sourceLabel, vehicleEventDetailsLabel } from "@/lib/vehicle-details/vehicle-details-formatters";
import { beginVehicleDetailsRefresh, failVehicleDetailsRefresh, initialVehicleDetailsRequestState, succeedVehicleDetailsRefresh } from "@/lib/vehicle-details/vehicle-details-request-state";
import { useAuth } from "@/components/auth-provider";
import { hasPermission } from "@/lib/auth/auth-contract";
import { useI18n } from "../i18n/client";

function alertTone(status: string): string { return status === "OPEN" ? "badge badge-alert-open" : "badge badge-alert-resolved"; }
function deliveryTone(status: string): string { return status === "SENT" ? "badge badge-delivery-sent" : status === "FAILED" ? "badge badge-delivery-failed" : status === "PENDING" ? "badge badge-delivery-pending" : "badge badge-delivery-none"; }
export function VehicleDetailsClient({ initialData }: Readonly<{ initialData: VehicleDetailsResponse }>) {
  const { locale, t } = useI18n();
  const auth = useAuth(); const canMap = auth !== null && hasPermission(auth, "map.view"); const canTrips = auth !== null && hasPermission(auth, "trips.view");
  const [state, setState] = useState(() => initialVehicleDetailsRequestState(initialData)); const stateRef = useRef(state); const active = useRef(false); const controller = useRef<AbortController | null>(null);
  useEffect(() => { stateRef.current = state; }, [state]);
  const refresh = useCallback(async () => { if (active.current) return; const begun = beginVehicleDetailsRefresh(stateRef.current); if (begun === stateRef.current) return; stateRef.current = begun; active.current = true; setState(begun); const generation = begun.generation; const nextController = new AbortController(); controller.current = nextController; try { const response = await fetch(`/api/vehicles/${begun.data.vehicle.id}/details`, { cache: "no-store", signal: nextController.signal, headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(); const data = parseVehicleDetailsResponse(await response.json()); if (!nextController.signal.aborted) { const next = succeedVehicleDetailsRefresh(stateRef.current, generation, data); stateRef.current = next; setState(next); } } catch { if (!nextController.signal.aborted) { const next = failVehicleDetailsRefresh(stateRef.current, generation); stateRef.current = next; setState(next); } } finally { if (generation === stateRef.current.generation) active.current = false; } }, []);
  useEffect(() => { const timer = window.setInterval(() => void refresh(), 30_000); return () => { window.clearInterval(timer); controller.current?.abort(); active.current = false; }; }, [refresh]);
  const { data } = state;
  return <>
    <header className="hero vehicle-details-hero"><p className="eyebrow">{t("vehicle.eyebrow")}</p><h1>{data.vehicle.name}</h1><div className="metadata"><span>{t("vehicle.generated")} <strong>{formatVehicleTimestamp(data.generatedAt, locale)}</strong></span>{canMap && <Link href="/map">{t("vehicle.openMap")}</Link>}{canTrips && <Link href={`/vehicles/${data.vehicle.id}/trips`}>{t("vehicle.trips")}</Link>}{canTrips && <Link href={`/vehicles/${data.vehicle.id}/track`}>{t("vehicle.history")}</Link>}</div></header>
    <div className="vehicle-details-actions"><button type="button" onClick={() => void refresh()} disabled={state.loading}>{state.loading ? t("common.refreshing") : t("common.refresh")}</button>{state.loading && <span aria-live="polite">{t("vehicle.refreshing")}</span>}</div>
    {state.refreshError && <section className="notice" role="alert"><span>⚠</span><div><strong>{t("vehicle.refreshError")}</strong><span>{t("vehicle.refreshFallback")}</span></div></section>}
    <div className="vehicle-details-grid">
      <section className="details-section"><h2>{t("vehicle.currentState")}</h2>{data.currentState === null ? <p className="details-empty">{t("vehicle.positionUnavailable")}</p> : <dl className="details-list"><div><dt>{t("vehicle.positionStatus")}</dt><dd><span className={data.currentState.freshness === "FRESH" ? "badge badge-fresh" : "badge badge-stale"}>{freshnessLabel(data.currentState.freshness, locale)}</span></dd></div><div><dt>{t("map.vehicle.speed")}</dt><dd>{formatVehicleSpeed(data.currentState.speedKph, locale)}</dd></div><div><dt>{t("map.vehicle.positionTime")}</dt><dd><time dateTime={data.currentState.position.observedAt}>{formatVehicleTimestamp(data.currentState.position.observedAt, locale)}</time></dd></div><div><dt>{t("map.vehicle.age")}</dt><dd>{formatVehicleAge(data.currentState.position.observedAt, data.generatedAt, locale)}</dd></div></dl>}</section>
      <section className="details-section"><h2>{t("vehicle.today")}</h2>{data.today === null ? <p className="details-empty">{t("vehicle.todayUnavailable")}</p> : <><dl className="details-list"><div><dt>{t("vehicle.todayDistance")}</dt><dd>{formatVehicleDistance(data.today.distanceMeters, locale)}</dd></div><div><dt>{t("vehicle.movementTime")}</dt><dd>{formatVehicleDuration(data.today.movementDurationSeconds, locale)}</dd></div><div><dt>{t("vehicle.maxSpeed")}</dt><dd>{formatVehicleSpeed(data.today.maxSpeedKph, locale)}</dd></div><div><dt>{t("vehicle.quality")}</dt><dd>{qualityLabel(data.today.quality, locale)}</dd></div></dl><p className="details-secondary">{t("vehicle.source")} {sourceLabel(data.today.source, locale)}</p>{data.today.isStale && <p className="details-warning">{t("vehicle.statsStale")}</p>}{data.today.isDegraded && <p className="details-warning">{t("vehicle.statsDegraded")}</p>}</>}</section>
      <section className="details-section"><h2>{t("vehicle.activeEvents")}</h2>{data.activeAlerts.length === 0 ? <p className="details-empty">{t("vehicle.noActiveEvents")}</p> : <ul className="details-events">{data.activeAlerts.map((alert) => <li key={alert.type}><strong>{alertTypeLabel(alert.type, locale)}</strong><time dateTime={alert.openedAt}>{t("vehicle.eventOpened")} {formatVehicleTimestamp(alert.openedAt, locale)}</time></li>)}</ul>}</section>
      <section className="details-section details-recent"><h2>{t("vehicle.recentEvents")}</h2>{data.recentEvents.length === 0 ? <p className="details-empty">{t("vehicle.noRecentEvents")}</p> : <ul className="details-events">{data.recentEvents.map((event) => <li key={event.id}><div className="details-event-heading"><strong>{alertTypeLabel(event.type, locale)}</strong><span className={alertTone(event.status)}>{alertStatusLabel(event.status, locale)}</span><span className={deliveryTone(event.notificationDeliveryStatus)}>{notificationDeliveryLabel(event.notificationDeliveryStatus, locale)}</span></div><span>{t("vehicle.eventOpened")} <time dateTime={event.openedAt}>{formatVehicleTimestamp(event.openedAt, locale)}</time></span>{event.resolvedAt && <span>{t("vehicle.eventResolved")} <time dateTime={event.resolvedAt}>{formatVehicleTimestamp(event.resolvedAt, locale)}</time></span>}<small>{vehicleEventDetailsLabel(event, locale)}</small></li>)}</ul>}</section>
    </div>
  </>;
}
