export const POSITION_HISTORY_POPULATION_RUN_LEASE_DURATION_MS = 120_000;
export const POSITION_HISTORY_POPULATION_RUN_HEARTBEAT_MS = 30_000;
export const POSITION_HISTORY_POPULATION_RUN_CHUNK_WINDOWS = 24;

export const POSITION_HISTORY_POPULATION_RUN_FAILURE_CODE = Object.freeze({
  EXECUTION_FAILED: "HISTORY_POPULATION_EXECUTION_FAILED",
  WORKER_FAILED: "HISTORY_POPULATION_WORKER_FAILED",
} as const);
