export const DAILY_STATS_REPOSITORY = Symbol("DAILY_STATS_REPOSITORY");
export const DASHBOARD_QUERY_REPOSITORY = Symbol("DASHBOARD_QUERY_REPOSITORY");
const DASHBOARD_CLOCK = Symbol("DASHBOARD_CLOCK");

export { DASHBOARD_CLOCK };
