export const EQU_GPS_TRANSPORT = Symbol("EQU_GPS_TRANSPORT");
export const OFFICIAL_EQU_GPS_CLIENT = Symbol("OFFICIAL_EQU_GPS_CLIENT");
export const WEB_RUNS_CLIENT = Symbol("WEB_RUNS_CLIENT");
export const WEB_VEHICLE_DETAILS_CLIENT = Symbol("WEB_VEHICLE_DETAILS_CLIENT");
export const WEB_SPEED_EVENTS_CLIENT = Symbol("WEB_SPEED_EVENTS_CLIENT");
export const WEB_ROUTE_CLIENT = Symbol("WEB_ROUTE_CLIENT");
export const SESSION_TOKEN_PROVIDER = Symbol("SESSION_TOKEN_PROVIDER");
