import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { AuthRole } from "../../generated/prisma/enums";
import type { DatabaseService } from "../database/database.service";
import { ADMIN_CARDINALITY_ADVISORY_LOCK_KEY, AdminUsersError, AdminUsersService, DEFAULT_ADMIN_USER_SECURITY, type AdminUserSecurity } from "./admin-users.service";
import { hashPassword, verifyPassword } from "./password";

const now = new Date("2026-08-12T12:00:00.000Z");
type Row = { id: string; login: string; normalizedLogin: string; role: AuthRole; disabled: boolean; mustChangePassword: boolean; passwordHashVersion: number; passwordSalt: Uint8Array; passwordHash: Uint8Array; passwordChangedAt: Date | null; createdAt: Date; updatedAt: Date };
const row = (id: string, role: AuthRole, disabled = false): Row => ({ id, login: id, normalizedLogin: id, role, disabled, mustChangePassword: false, passwordHashVersion: 1, passwordSalt: new Uint8Array([1]), passwordHash: new Uint8Array([2]), passwordChangedAt: null, createdAt: now, updatedAt: now });

function fixture(initial: readonly Row[] = [row("actor", AuthRole.ADMIN), row("target", AuthRole.USER)], securityOverride?: AdminUserSecurity) {
  const users = new Map(initial.map((user) => [user.id, { ...user }])); const permissions = new Map<string, string[]>(initial.map((user) => [user.id, user.role === AuthRole.USER ? ["reports.view"] : []])); const sessions = new Map<string, string[]>(initial.map((user) => [user.id, [`${user.id}-session`]])); const dbArguments: unknown[] = []; const hashes: string[] = []; let generated = 0; let locks = 0; let activeLock: Promise<void> = Promise.resolve();
  const withPermissions = (user: Row) => ({ ...user, permissions: (permissions.get(user.id) ?? []).map((key) => ({ key })) });
  function transaction() { let release: (() => void) | undefined; return {
    $executeRaw: async () => { const previous = activeLock; activeLock = new Promise<void>((resolve) => { release = resolve; }); await previous; locks += 1; return 1; },
    authUser: {
      create: async ({ data }: { data: Record<string, unknown> }) => { dbArguments.push(data); if ([...users.values()].some((user) => user.normalizedLogin === data.normalizedLogin)) throw Object.assign(new Error("database duplicate details"), { code: "P2002" }); const created = { ...row(`created-${users.size}`, data.role as AuthRole), ...data, id: `created-${users.size}`, createdAt: now, updatedAt: now, passwordChangedAt: null } as Row; users.set(created.id, created); permissions.set(created.id, []); sessions.set(created.id, []); return withPermissions(created); },
      findUnique: async ({ where }: { where: { id: string } }) => { const user = users.get(where.id); return user ? withPermissions(user) : null; },
      findUniqueOrThrow: async ({ where }: { where: { id: string } }) => { const user = users.get(where.id); if (!user) throw new Error("missing"); return withPermissions(user); },
      update: async ({ where, data }: { where: { id: string }; data: Partial<Row> }) => { dbArguments.push(data); const user = users.get(where.id); if (!user) throw new Error("missing"); Object.assign(user, data, { updatedAt: now }); return withPermissions(user); },
      count: async () => [...users.values()].filter((user) => user.role === AuthRole.ADMIN && !user.disabled).length,
    },
    authUserPermission: { deleteMany: async ({ where }: { where: { userId: string } }) => { permissions.set(where.userId, []); }, createMany: async ({ data }: { data: { userId: string; key: string }[] }) => { for (const item of data) permissions.set(item.userId, [...(permissions.get(item.userId) ?? []), item.key]); } },
    authSession: { deleteMany: async ({ where }: { where: { userId: string } }) => { sessions.set(where.userId, []); } },
    release: () => release?.(),
  }; }
  const client = {
    authUser: { findMany: async () => [...users.values()].sort((a, b) => a.normalizedLogin.localeCompare(b.normalizedLogin)).map(withPermissions), findUnique: async ({ where }: { where: { id: string } }) => { const user = users.get(where.id); return user ? withPermissions(user) : null; } },
    $transaction: async (callback: (tx: ReturnType<typeof transaction>) => Promise<unknown>) => { const tx = transaction(); try { return await callback(tx); } finally { tx.release(); } },
  };
  const security: AdminUserSecurity = { generatePassword: () => { generated += 1; return `${"A".repeat(23)}${generated}`; }, hashPassword: async (password) => { hashes.push(password); return { version: 1, salt: new Uint8Array([7, 8]), hash: new Uint8Array([9, 10]) }; } };
  return { service: new AdminUsersService({ getClient: () => client } as unknown as DatabaseService, securityOverride ?? security), users, permissions, sessions, dbArguments, hashes, locks: () => locks };
}

test("create is atomic, hashes the generated secret, expands USER dependencies, and never persists plaintext", async () => { const state = fixture(); const result = await state.service.create({ login: "Dispatcher.1", role: "USER", permissions: ["trips.view"] }); assert.equal(result.temporaryPassword.length, 24); assert.deepEqual(state.hashes, [result.temporaryPassword]); assert.equal(result.user.disabled, false); assert.equal(result.user.mustChangePassword, true); assert.deepEqual(result.user.permissions, ["vehicles.view", "trips.view"]); assert.equal(JSON.stringify(state.dbArguments).includes(result.temporaryPassword), false); assert.equal("temporaryPassword" in await state.service.detail(result.user.id), false); assert.equal(JSON.stringify(await state.service.list()).includes(result.temporaryPassword), false); });
test("ADMIN creation persists zero permission rows and secret-bearing client fields are rejected", async () => { const state = fixture(); const result = await state.service.create({ login: "Second.Admin", role: "ADMIN", permissions: [] }); assert.deepEqual(state.permissions.get(result.user.id), []); assert.deepEqual(result.user.permissions, []); assert.equal(state.locks(), 1); await assert.rejects(state.service.create({ login: "bad", role: "USER", permissions: [], password: "client-secret" }), (error: unknown) => error instanceof AdminUsersError && error.code === "INVALID_INPUT"); });
test("duplicate normalized login and unknown permission become stable safe errors", async () => { const state = fixture(); await assert.rejects(state.service.create({ login: "ACTOR", role: "ADMIN", permissions: [] }), (error: unknown) => error instanceof AdminUsersError && error.code === "DUPLICATE_LOGIN" && !error.message.includes("database")); await assert.rejects(state.service.create({ login: "valid-user", role: "USER", permissions: ["unknown"] }), (error: unknown) => error instanceof AdminUsersError && error.code === "INVALID_INPUT"); });

test("access updates use complete replace-set semantics; promotion clears rows and demotion requires an explicit normalized set", async () => { const state = fixture([row("actor", AuthRole.ADMIN), row("target", AuthRole.USER), row("other-admin", AuthRole.ADMIN)]); await state.service.updateAccess("actor", "target", { role: "USER", permissions: ["historyAdmin.populate"] }); assert.deepEqual(state.permissions.get("target"), ["historyAdmin.view", "historyAdmin.populate"]); await state.service.updateAccess("actor", "target", { role: "ADMIN", permissions: [] }); assert.deepEqual(state.permissions.get("target"), []); await assert.rejects(state.service.updateAccess("actor", "target", { role: "USER" }), (error: unknown) => error instanceof AdminUsersError && error.code === "INVALID_INPUT"); const demoted = await state.service.updateAccess("actor", "target", { role: "USER", permissions: ["trips.view"] }); assert.deepEqual(demoted.permissions, ["vehicles.view", "trips.view"]); });
test("self demotion, self disable, and self admin-reset are backend protected", async () => { const state = fixture(); for (const operation of [() => state.service.updateAccess("actor", "actor", { role: "USER", permissions: [] }), () => state.service.disable("actor", "actor"), () => state.service.resetPassword("actor", "actor")]) await assert.rejects(operation(), (error: unknown) => error instanceof AdminUsersError && error.code === "SELF_PROTECTED"); });
test("last enabled ADMIN cannot be disabled or demoted, while disabled ADMIN is not counted", async () => { const state = fixture([row("actor", AuthRole.ADMIN), row("disabled-admin", AuthRole.ADMIN, true)]); await assert.rejects(state.service.disable("other", "actor"), (error: unknown) => error instanceof AdminUsersError && error.code === "LAST_ENABLED_ADMIN"); await assert.rejects(state.service.updateAccess("other", "actor", { role: "USER", permissions: [] }), (error: unknown) => error instanceof AdminUsersError && error.code === "LAST_ENABLED_ADMIN"); await state.service.enable("disabled-admin"); await state.service.disable("other", "actor"); assert.equal(state.users.get("actor")?.disabled, true); });

test("disable atomically revokes only target sessions; enable preserves access and never restores sessions", async () => { const state = fixture(); const beforePermissions = [...(state.permissions.get("target") ?? [])]; await state.service.disable("actor", "target"); assert.equal(state.users.get("target")?.disabled, true); assert.deepEqual(state.sessions.get("target"), []); assert.deepEqual(state.sessions.get("actor"), ["actor-session"]); await state.service.enable("target"); assert.equal(state.users.get("target")?.disabled, false); assert.deepEqual(state.permissions.get("target"), beforePermissions); assert.deepEqual(state.sessions.get("target"), []); });
test("reset replaces hash material, sets mustChangePassword, revokes sessions, and returns a non-recoverable one-time secret", async () => { const state = fixture(); const result = await state.service.resetPassword("actor", "target"); assert.deepEqual(state.hashes, [result.temporaryPassword]); assert.equal(state.users.get("target")?.mustChangePassword, true); assert.deepEqual(state.sessions.get("target"), []); assert.equal(JSON.stringify(state.dbArguments).includes(result.temporaryPassword), false); assert.equal("temporaryPassword" in await state.service.detail("target"), false); });
test("real reset material rejects the old password and verifies the generated temporary password", async () => { const oldPassword = "old secure password value"; const old = await hashPassword(oldPassword); const target = { ...row("target", AuthRole.USER), passwordHashVersion: old.version, passwordSalt: new Uint8Array(old.salt), passwordHash: new Uint8Array(old.hash) }; const state = fixture([row("actor", AuthRole.ADMIN), target], DEFAULT_ADMIN_USER_SECURITY); const result = await state.service.resetPassword("actor", "target"); const updated = state.users.get("target")!; const material = { version: updated.passwordHashVersion, salt: updated.passwordSalt, hash: updated.passwordHash }; assert.equal(await verifyPassword(oldPassword, material), false); assert.equal(await verifyPassword(result.temporaryPassword, material), true); });

test("one advisory lock serializes concurrent enabled-ADMIN reductions so zero is impossible", async () => { const state = fixture([row("admin-a", AuthRole.ADMIN), row("admin-b", AuthRole.ADMIN)]); const outcomes = await Promise.allSettled([state.service.disable("manager", "admin-a"), state.service.disable("manager", "admin-b")]); assert.equal(outcomes.filter((outcome) => outcome.status === "fulfilled").length, 1); assert.equal(outcomes.filter((outcome) => outcome.status === "rejected" && outcome.reason instanceof AdminUsersError && outcome.reason.code === "LAST_ENABLED_ADMIN").length, 1); assert.equal([...state.users.values()].filter((user) => user.role === AuthRole.ADMIN && !user.disabled).length, 1); assert.equal(state.locks(), 2); });
test("advisory lock key is fixed, uses executeRaw for PostgreSQL void, and precedes count/mutation", () => { assert.equal(ADMIN_CARDINALITY_ADVISORY_LOCK_KEY, 1_706_170_002); const source = readFileSync("src/modules/auth/admin-users.service.ts", "utf8"); assert.match(source, /\$executeRaw`SELECT pg_advisory_xact_lock/); assert.doesNotMatch(source, /\$queryRaw`SELECT pg_advisory_xact_lock/); assert.ok(source.indexOf("lockAdminCardinality(transaction)") < source.indexOf("enabledAdmins = await transaction.authUser.count")); });
