import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { AuthRole } from "../../generated/prisma/enums";
import type { DatabaseService } from "../database/database.service";
import { AuthService, InvalidCredentialsError } from "./auth.service";
import { hashPassword } from "./password";

const now = new Date("2026-08-12T12:00:00.000Z");
async function fixture() {
  const material = await hashPassword("current secure password"); let sessionCreates: Record<string, unknown>[] = []; let sessionDeletes: Record<string, unknown>[] = []; let updated: Record<string, unknown> | null = null; let finalAuthorityRows: readonly Readonly<{ id: string }>[] = [{ id: "user-id" }]; let loginTransactions = 0;
  const user = { id: "user-id", login: "User.One", normalizedLogin: "user.one", role: AuthRole.USER, disabled: false, mustChangePassword: false, passwordHashVersion: material.version, passwordSalt: new Uint8Array(material.salt), passwordHash: new Uint8Array(material.hash), passwordChangedAt: null, createdAt: now, updatedAt: now, permissions: [{ key: "trips.view" }] };
  const transaction = { $queryRaw: async () => { loginTransactions += 1; return finalAuthorityRows; }, authUser: { updateMany: async ({ data }: { data: Record<string, unknown> }) => { updated = data; return { count: 1 }; }, findUniqueOrThrow: async () => ({ ...user, ...updated, permissions: user.permissions }) }, authSession: { deleteMany: async ({ where }: { where: Record<string, unknown> }) => { sessionDeletes.push(where); }, create: async ({ data }: { data: Record<string, unknown> }) => { sessionCreates.push(data); } } };
  const client = { authUser: { findUnique: async ({ where }: { where: Record<string, unknown> }) => where.normalizedLogin === "user.one" || where.id === user.id ? user : null }, authSession: { create: async ({ data }: { data: Record<string, unknown> }) => { sessionCreates.push(data); }, findUnique: async () => null, deleteMany: async ({ where }: { where: Record<string, unknown> }) => { sessionDeletes.push(where); } }, $transaction: async (callback: (value: typeof transaction) => Promise<unknown>) => callback(transaction) };
  return { service: new AuthService({ getClient: () => client } as unknown as DatabaseService), user, sessionCreates, sessionDeletes, updated: () => updated, setFinalAuthority: (allowed: boolean) => { finalAuthorityRows = allowed ? [{ id: user.id }] : []; }, loginTransactions: () => loginTransactions };
}
test("valid login revalidates under transaction and creates one hashed seven-day server session", async () => { const state = await fixture(); const result = await state.service.login("USER.ONE", "current secure password", now); assert.equal(result.user.login, "User.One"); assert.deepEqual(result.user.permissions, ["vehicles.view", "trips.view"]); assert.equal("passwordHash" in result.user, false); assert.equal(state.loginTransactions(), 1); assert.equal(state.sessionCreates.length, 1); assert.equal(state.sessionCreates[0]?.tokenHash instanceof Uint8Array, true); assert.equal(JSON.stringify(state.sessionCreates[0]).includes(result.token), false); assert.equal((state.sessionCreates[0]?.expiresAt as Date).getTime() - now.getTime(), 7 * 24 * 60 * 60 * 1_000); });
test("stale verified password material creates zero sessions after final transactional CAS fails", async () => { const state = await fixture(); state.setFinalAuthority(false); await assert.rejects(state.service.login("user.one", "current secure password", now), InvalidCredentialsError); assert.equal(state.loginTransactions(), 1); assert.equal(state.sessionCreates.length, 0); });
test("disabled transition before final transactional authority check creates zero sessions", async () => { const state = await fixture(); state.setFinalAuthority(false); await assert.rejects(state.service.login("user.one", "current secure password", now), (error: unknown) => error instanceof InvalidCredentialsError && error.message === "Неверный логин или пароль"); assert.equal(state.sessionCreates.length, 0); });
test("login final authority check locks the exact verified credential state before session creation", () => { const source = readFileSync("src/modules/auth/auth.service.ts", "utf8"); const lock = source.indexOf("FOR UPDATE"); const create = source.indexOf("transaction.authSession.create", lock); assert.ok(lock > 0); assert.ok(create > lock); assert.match(source, /password_hash_version/); assert.match(source, /password_salt/); assert.match(source, /password_hash/); assert.match(source, /disabled[^\n]*= false/); });
test("unknown and wrong password use the same generic error", async () => { const state = await fixture(); await assert.rejects(state.service.login("missing", "wrong password value", now), InvalidCredentialsError); await assert.rejects(state.service.login("user.one", "wrong password value", now), InvalidCredentialsError); });
test("wrong current password mutates nothing; success replaces hash, clears flag, deletes all sessions, and creates one", async () => { const state = await fixture(); const principal = { id: state.user.id, login: state.user.login, role: state.user.role, permissions: [], mustChangePassword: true, sessionTokenHash: new Uint8Array(32) }; await assert.rejects(state.service.changePassword(principal, "wrong password value", "next secure password", now), InvalidCredentialsError); assert.equal(state.sessionCreates.length, 0); assert.equal(state.updated(), null); const result = await state.service.changePassword(principal, "current secure password", "next secure password", now); assert.equal(result.user.mustChangePassword, false); assert.equal(state.sessionDeletes.length, 1); assert.deepEqual(state.sessionDeletes[0], { userId: state.user.id }); assert.equal(state.sessionCreates.length, 1); assert.notDeepEqual(state.updated()?.passwordHash, state.user.passwordHash); });
test("session authentication is read-only and rejects exact-expiry and disabled users", async () => { let reads = 0; let writes = 0; const baseUser = { id: "user-id", login: "user", normalizedLogin: "user", role: AuthRole.USER, disabled: false, mustChangePassword: false, passwordHashVersion: 1, passwordSalt: new Uint8Array(16), passwordHash: new Uint8Array(32), passwordChangedAt: null, createdAt: now, updatedAt: now, permissions: [{ key: "fleet.view" }] }; let row: object | null = { expiresAt: new Date(now.getTime() + 1), user: baseUser }; const client = { authSession: { findUnique: async () => { reads += 1; return row; }, update: async () => { writes += 1; } } }; const service = new AuthService({ getClient: () => client } as unknown as DatabaseService); assert.equal((await service.authenticate("a".repeat(43), now))?.login, "user"); assert.equal(reads, 1); assert.equal(writes, 0); row = { expiresAt: now, user: baseUser }; assert.equal(await service.authenticate("b".repeat(43), now), null); row = { expiresAt: new Date(now.getTime() + 1), user: { ...baseUser, disabled: true } }; assert.equal(await service.authenticate("c".repeat(43), now), null); assert.equal(writes, 0); });
test("an existing opaque session observes current database permissions and role on every request", async () => { const baseUser = { id: "user-id", login: "user", normalizedLogin: "user", role: AuthRole.USER, disabled: false, mustChangePassword: false, passwordHashVersion: 1, passwordSalt: new Uint8Array(16), passwordHash: new Uint8Array(32), passwordChangedAt: null, createdAt: now, updatedAt: now }; let authority: { role: AuthRole; permissions: { key: string }[] } = { role: AuthRole.USER, permissions: [{ key: "reports.view" }] }; const client = { authSession: { findUnique: async () => ({ expiresAt: new Date(now.getTime() + 1), user: { ...baseUser, ...authority } }) } }; const service = new AuthService({ getClient: () => client } as unknown as DatabaseService); assert.deepEqual((await service.authenticate("a".repeat(43), now))?.permissions, ["reports.view"]); authority = { role: AuthRole.USER, permissions: [] }; assert.deepEqual((await service.authenticate("a".repeat(43), now))?.permissions, []); authority = { role: AuthRole.ADMIN, permissions: [] }; assert.equal((await service.authenticate("a".repeat(43), now))?.role, AuthRole.ADMIN); });
