export const VEHICLE_TRACK_QUERY_REPOSITORY = Symbol("VEHICLE_TRACK_QUERY_REPOSITORY");
export const VEHICLE_TRACK_OVERVIEW_QUERY_REPOSITORY = Symbol("VEHICLE_TRACK_OVERVIEW_QUERY_REPOSITORY");
export const VEHICLE_TRACK_CLOCK = Symbol("VEHICLE_TRACK_CLOCK");
