import { AUTH_PERMISSIONS, type AuthPermission } from "../auth/auth-contract";

export type AdminManagedUser = Readonly<{ id: string; login: string; role: "ADMIN" | "USER"; disabled: boolean; mustChangePassword: boolean; permissions: readonly AuthPermission[]; createdAt: string; updatedAt: string }>;

const permissionDependencies = { "trips.view": Object.freeze(["vehicles.view"] as const), "historyAdmin.populate": Object.freeze(["historyAdmin.view"] as const) } satisfies Readonly<Partial<Record<AuthPermission, readonly AuthPermission[]>>>;
export const PERMISSION_DEPENDENCIES: Readonly<Partial<Record<AuthPermission, readonly AuthPermission[]>>> = Object.freeze(permissionDependencies);

export function normalizePermissionSelection(values: readonly AuthPermission[]): readonly AuthPermission[] { const selected = new Set<AuthPermission>(); const visit = (permission: AuthPermission): void => { if (selected.has(permission)) return; selected.add(permission); for (const dependency of PERMISSION_DEPENDENCIES[permission] ?? []) visit(dependency); }; for (const value of values) visit(value); return Object.freeze(AUTH_PERMISSIONS.filter((permission) => selected.has(permission))); }

export function parseAdminManagedUser(value: unknown): AdminManagedUser | null { if (typeof value !== "object" || value === null) return null; const user = value as Record<string, unknown>; if (typeof user.id !== "string" || typeof user.login !== "string" || (user.role !== "ADMIN" && user.role !== "USER") || typeof user.disabled !== "boolean" || typeof user.mustChangePassword !== "boolean" || typeof user.createdAt !== "string" || typeof user.updatedAt !== "string" || !Array.isArray(user.permissions) || user.permissions.some((key) => !AUTH_PERMISSIONS.includes(key as AuthPermission))) return null; return Object.freeze({ id: user.id, login: user.login, role: user.role, disabled: user.disabled, mustChangePassword: user.mustChangePassword, permissions: Object.freeze(user.permissions as AuthPermission[]), createdAt: user.createdAt, updatedAt: user.updatedAt }); }
export function parseAdminManagedUsers(value: unknown): readonly AdminManagedUser[] | null { if (!Array.isArray(value)) return null; const users = value.map(parseAdminManagedUser); return users.some((user) => !user) ? null : Object.freeze(users as AdminManagedUser[]); }
export function parseOneTimePasswordResult(value: unknown): Readonly<{ user: AdminManagedUser; temporaryPassword: string }> | null { if (typeof value !== "object" || value === null) return null; const result = value as Record<string, unknown>; const user = parseAdminManagedUser(result.user); return user && typeof result.temporaryPassword === "string" && /^[A-Za-z0-9_-]{24}$/.test(result.temporaryPassword) ? Object.freeze({ user, temporaryPassword: result.temporaryPassword }) : null; }
