import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { normalizePermissionSelection, parseAdminManagedUser, parseOneTimePasswordResult } from "./admin-users-contract";

const safeUser = { id: "id", login: "user", role: "USER", disabled: false, mustChangePassword: true, permissions: ["trips.view", "vehicles.view"], createdAt: "2026-08-12T12:00:00.000Z", updatedAt: "2026-08-12T12:00:00.000Z" } as const;
test("web permission selection explains and applies the same source-controlled dependencies", () => { assert.deepEqual(normalizePermissionSelection(["trips.view"]), ["vehicles.view", "trips.view"]); assert.deepEqual(normalizePermissionSelection(["historyAdmin.populate"]), ["historyAdmin.view", "historyAdmin.populate"]); });
test("safe admin user parser rejects hashes, unknown permissions, and malformed one-time secrets", () => { assert.ok(parseAdminManagedUser(safeUser)); assert.equal(parseAdminManagedUser({ ...safeUser, permissions: ["users.manage"] }), null); assert.equal(parseOneTimePasswordResult({ user: safeUser, temporaryPassword: "short" }), null); assert.ok(parseOneTimePasswordResult({ user: safeUser, temporaryPassword: "A".repeat(24) })); });
test("create/detail UI has no password input, delete, email, persistence, or GPS population action", () => { const create = readFileSync("src/components/admin-user-create-form.tsx", "utf8"); const detail = readFileSync("src/components/admin-user-detail.tsx", "utf8"); const secret = readFileSync("src/components/one-time-password.tsx", "utf8"); assert.doesNotMatch(create, /type=["']password/); assert.doesNotMatch(`${create}${detail}`, /localStorage|sessionStorage|indexedDB|DELETE|email|Удалить пользователя|Запустить|Дозаполнить/); assert.match(secret, /Показать/); assert.match(secret, /Скрыть/); assert.match(secret, /Скопировать/); assert.match(secret, /Готово/); assert.match(secret, /useState\(false\)/); assert.doesNotMatch(secret, /writeText\([^)]*\)[^]*useEffect/); });
