export const POSITION_HISTORY_BACKFILL_REPOSITORY = Symbol("POSITION_HISTORY_BACKFILL_REPOSITORY");
export const POSITION_HISTORY_BACKFILL_CLOCK = Symbol("POSITION_HISTORY_BACKFILL_CLOCK");
export const POSITION_HISTORY_BACKFILL_SLEEPER = Symbol("POSITION_HISTORY_BACKFILL_SLEEPER");
