export {
  classifyPositionHistoryHistoricalWindowProviderFailure as classifyPositionHistoryBackfillProviderFailure,
  recordPositionHistoryHistoricalWindowProviderFailure as recordPositionHistoryBackfillProviderFailure,
  recordedPositionHistoryHistoricalWindowProviderFailure as recordedPositionHistoryBackfillProviderFailure,
  type PositionHistoryHistoricalWindowProviderFailureDiagnostic as PositionHistoryBackfillProviderFailureDiagnostic,
} from "../position-history-historical-window/position-history-historical-window-failure-diagnostics";
