import { POSITION_HISTORY_HISTORICAL_WINDOW_MAX_DURATION_MS } from "../position-history-historical-window";

export const POSITION_HISTORY_BACKFILL_MAX_TARGET_MS = 7 * 24 * 60 * 60 * 1_000;
export const POSITION_HISTORY_BACKFILL_WINDOW_MS = POSITION_HISTORY_HISTORICAL_WINDOW_MAX_DURATION_MS;
