export const POSITION_HISTORY_HISTORICAL_WINDOW_MAX_DURATION_MS = 6 * 60 * 60 * 1_000;
export const POSITION_HISTORY_HISTORICAL_WINDOW_MAX_ROWS = 10_000;
export const POSITION_HISTORY_HISTORICAL_WINDOW_MAX_ATTEMPTS = 3;
export const POSITION_HISTORY_HISTORICAL_WINDOW_MAX_RETRY_AFTER_MS = 60_000;
