export const SYNC_SCHEDULER_CLOCK = Symbol("SYNC_SCHEDULER_CLOCK");
export const SCHEDULER_TIMER_ADAPTER = Symbol("SCHEDULER_TIMER_ADAPTER");
export const SYNC_SCHEDULER_TIMEOUT_FACTORY = Symbol("SYNC_SCHEDULER_TIMEOUT_FACTORY");
