export const ALERT_EVENTS_REPOSITORY = Symbol("ALERT_EVENTS_REPOSITORY");
export const ALERT_EVENTS_QUERY_REPOSITORY = Symbol("ALERT_EVENTS_QUERY_REPOSITORY");
export const ALERT_EVENTS_QUERY_CLOCK = Symbol("ALERT_EVENTS_QUERY_CLOCK");
