export const POSITION_HISTORY_CONTINUOUS_REPOSITORY = Symbol("POSITION_HISTORY_CONTINUOUS_REPOSITORY");
export const POSITION_HISTORY_CONTINUOUS_CLOCK = Symbol("POSITION_HISTORY_CONTINUOUS_CLOCK");
export const POSITION_HISTORY_CONTINUOUS_SLEEPER = Symbol("POSITION_HISTORY_CONTINUOUS_SLEEPER");
export const POSITION_HISTORY_CONTINUOUS_TIMER = Symbol("POSITION_HISTORY_CONTINUOUS_TIMER");
