export const POSITION_HISTORY_REPLAY_WINDOW_MS = 6 * 60 * 60 * 1_000;
export const POSITION_HISTORY_ADAPTIVE_FETCH_DURATIONS_MS = Object.freeze([
  POSITION_HISTORY_REPLAY_WINDOW_MS,
  3 * 60 * 60 * 1_000,
  60 * 60 * 1_000,
] as const);
export const POSITION_HISTORY_REPLAY_DAILY_DAYS = 7;
export const POSITION_HISTORY_REPLAY_ROLLING_DAYS = 90;
export const POSITION_HISTORY_REPLAY_LEASE_DURATION_MS = 120_000;
export const POSITION_HISTORY_REPLAY_HEARTBEAT_MS = 30_000;
export const POSITION_HISTORY_REPLAY_STABLE_FAILURE_BACKOFF_MS = 6 * 60 * 60 * 1_000;
export const POSITION_HISTORY_REPLAY_FAILURE_BACKOFF_MS = Object.freeze([60_000, 120_000, 240_000, 480_000, 960_000, 1_800_000] as const);
export const POSITION_HISTORY_COORDINATED_REQUEST_START_BUDGET = 5;
export const POSITION_HISTORY_CAPACITY_RECENT_STARTS_PER_MINUTE = 20;
export const POSITION_HISTORY_CAPACITY_DAILY_STARTS_PER_MINUTE = 2;
export const POSITION_HISTORY_CAPACITY_ROLLING_STARTS_PER_MINUTE = 4;
export const POSITION_HISTORY_CAPACITY_OVERDUE_DAILY_STARTS_PER_MINUTE = 3;
export const POSITION_HISTORY_CAPACITY_OVERDUE_ROLLING_STARTS_PER_MINUTE = 5;
