import { DateTime } from "luxon";
import type { VehicleTrackRange } from "../vehicle-track/vehicle-track-range";
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
export type FleetActivityReportDate = Readonly<{ date: string; range: VehicleTrackRange; defaulted: boolean }>;
function validDate(value: unknown, timezone: string): string | null { if (typeof value !== "string" || !DATE_PATTERN.test(value)) return null; const parsed = DateTime.fromISO(value, { zone: timezone }); return parsed.isValid && parsed.toISODate() === value ? value : null; }
export function currentBusinessDate(now: Date, timezone: string): string | null { if (!Number.isFinite(now.getTime())) return null; return DateTime.fromJSDate(now, { zone: "utc" }).setZone(timezone).toISODate(); }
export function resolveFleetActivityReportDateRange(date: string, now: Date, timezone: string): VehicleTrackRange | null { const selected = validDate(date, timezone); const today = currentBusinessDate(now, timezone); if (!selected || !today) return null; const start = DateTime.fromISO(selected, { zone: timezone }).startOf("day"); const current = DateTime.fromJSDate(now, { zone: "utc" }); const end = selected === today ? current : start.plus({ days: 1 }); return end.toMillis() > start.toMillis() ? Object.freeze({ from: start.toUTC().toISO()!, to: end.toUTC().toISO()! }) : null; }
export function resolveInitialFleetActivityReportDate(searchParams: Readonly<Record<string, string | string[] | undefined>>, now: Date, timezone: string): FleetActivityReportDate | null { const today = currentBusinessDate(now, timezone); if (!today) return null; const restored = validDate(searchParams.date, timezone); const date = restored ?? today; const range = resolveFleetActivityReportDateRange(date, now, timezone); return range ? Object.freeze({ date, range, defaulted: restored === null }) : null; }
export function previousBusinessDate(now: Date, timezone: string): string | null { const today = currentBusinessDate(now, timezone); return today ? DateTime.fromISO(today, { zone: timezone }).minus({ days: 1 }).toISODate() : null; }
